/** Major US cities — merged into location resolver */
export const US_CITIES: Record<string, string> = {
  "new york": "New York",
  nyc: "New York",
  brooklyn: "New York",
  manhattan: "New York",
  "los angeles": "Los Angeles",
  la: "Los Angeles",
  chicago: "Chicago",
  houston: "Houston",
  phoenix: "Phoenix",
  philadelphia: "Philadelphia",
  "san antonio": "San Antonio",
  "san diego": "San Diego",
  dallas: "Dallas",
  "san jose": "San Jose",
  austin: "Austin",
  jacksonville: "Jacksonville",
  "fort worth": "Fort Worth",
  columbus: "Columbus",
  charlotte: "Charlotte",
  indianapolis: "Indianapolis",
  "san francisco": "San Francisco",
  seattle: "Seattle",
  denver: "Denver",
  boston: "Boston",
  nashville: "Nashville",
  detroit: "Detroit",
  portland: "Portland",
  memphis: "Memphis",
  baltimore: "Baltimore",
  milwaukee: "Milwaukee",
  albuquerque: "Albuquerque",
  tucson: "Tucson",
  fresno: "Fresno",
  sacramento: "Sacramento",
  atlanta: "Atlanta",
  omaha: "Omaha",
  miami: "Miami",
  oakland: "Oakland",
  minneapolis: "Minneapolis",
  tulsa: "Tulsa",
  cleveland: "Cleveland",
  wichita: "Wichita",
  arlington: "Arlington",
  "new orleans": "New Orleans",
  tampa: "Tampa",
  honolulu: "Honolulu",
  anaheim: "Anaheim",
  "santa ana": "Santa Ana",
  riverside: "Riverside",
  "corpus christi": "Corpus Christi",
  lexington: "Lexington",
  henderson: "Henderson",
  stockton: "Stockton",
  "saint paul": "Saint Paul",
  "st paul": "Saint Paul",
  cincinnati: "Cincinnati",
  pittsburgh: "Pittsburgh",
  greensboro: "Greensboro",
  anchorage: "Anchorage",
  lincoln: "Lincoln",
  orlando: "Orlando",
  irvine: "Irvine",
  newark: "Newark",
  durham: "Durham",
  "st louis": "St. Louis",
  "saint louis": "St. Louis",
  "kansas city": "Kansas City",
  plano: "Plano",
  chandler: "Chandler",
  laredo: "Laredo",
  norfolk: "Norfolk",
  madison: "Madison",
  lubbock: "Lubbock",
  "baton rouge": "Baton Rouge",
  "jersey city": "Jersey City",
  chula: "Chula Vista",
  "chula vista": "Chula Vista",
  buffalo: "Buffalo",
  reno: "Reno",
  "fort wayne": "Fort Wayne",
  irving: "Irving",
  richmond: "Richmond",
  boise: "Boise",
  spokane: "Spokane",
  birmingham: "Birmingham",
  montgomery: "Montgomery",
  mobile: "Mobile",
  huntsville: "Huntsville",
  juneau: "Juneau",
  phoenixville: "Phoenix",
  hartford: "Hartford",
  providence: "Providence",
  charleston: "Charleston",
  columbia: "Columbia",
  des: "Des Moines",
  "des moines": "Des Moines",
  topeka: "Topeka",
  frankfort: "Frankfort",
  louisville: "Louisville",
  annapolis: "Annapolis",
  augusta: "Augusta",
  concord: "Concord",
  trenton: "Trenton",
  santa: "Santa Fe",
  "santa fe": "Santa Fe",
  raleigh: "Raleigh",
  bismarck: "Bismarck",
  pierre: "Pierre",
  cheyenne: "Cheyenne",
  helena: "Helena",
  salem: "Salem",
  olympia: "Olympia",
  carson: "Carson City",
  "carson city": "Carson City",
  harrisburg: "Harrisburg",
  dover: "Dover",
  montpelier: "Montpelier",
  charlestonwv: "Charleston",
  springfield: "Springfield",
  indianapolisin: "Indianapolis",
  lansing: "Lansing",
  jefferson: "Jefferson City",
  "jefferson city": "Jefferson City",
  oklahoma: "Oklahoma City",
  "oklahoma city": "Oklahoma City",
  little: "Little Rock",
  "little rock": "Little Rock",
  salt: "Salt Lake City",
  "salt lake": "Salt Lake City",
  "salt lake city": "Salt Lake City",
  boiseid: "Boise",
  phoenixaz: "Phoenix",
  "las vegas": "Las Vegas",
  vegas: "Las Vegas",
  "palo alto": "Palo Alto",
  "silicon valley": "San Francisco",
  menlo: "Menlo Park",
  "menlo park": "Menlo Park",
  cambridge: "Cambridge",
  bethesda: "Bethesda",
  arlingtonva: "Arlington",
  alexandria: "Alexandria",
  scottsdale: "Scottsdale",
  tempe: "Tempe",
  "beverly hills": "Beverly Hills",
  greenwich: "Greenwich",
  stamford: "Stamford",
  white: "White Plains",
  "white plains": "White Plains",
  "ann arbor": "Ann Arbor",
  "grand rapids": "Grand Rapids",
  "detroit metro": "Detroit",
  kalamazoo: "Kalamazoo",
  flint: "Flint",
  atherton: "Atherton",
  "mountain view": "Mountain View",
  cupertino: "Cupertino",
  sunnyvale: "Sunnyvale",
  "san mateo": "San Mateo",
  "redwood city": "Redwood City",
  woodside: "Woodside",
  hillsborough: "Hillsborough",
  "santa monica": "Santa Monica",
  pasadena: "Pasadena",
  eugene: "Eugene",
  rochester: "Rochester",
  albany: "Albany",
  syracuse: "Syracuse",
  savannah: "Savannah",
};
